[package]
name = 'aux'
version = '1.0.0'

[addresses]
aux = '_'
deployer_aux = '_'

[dev-addresses]
# this address is the resource account from 0x5E7C3 and seed amm
# go run ./go-util/aptos/cmd/calculate-resource-address -a 0x5E7C3 - s amm
aux = '0x4c8e0dc1b53b7759c9d8998685453a0e06565f054f3635a18d4928520eec676d'
deployer_aux = '0x8686'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'a2a3bf79b68823287f962bded2abfaefc688e71c'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.deployer]
local = '../deployer'
